server.port=${PORT:8081}

kafka.bootstrap-servers=${BOOTSTRAP_SERVER_URL:localhost:9092}

kafka.consumer.retry.max-attempts=${RETRY_MAX_ATTEMPTS:5}
kafka.consumer.retry.backoff-delay-ms=${RETRY_BACKOFF_DELAY_MS:1000}
kafka.consumer.concurrency=${CONSUMER_CONCURRENCY:1}
kafka.consumer.group=${CONSUMER_GROUP:filing-notification-sender}
kafka.consumer.topic.filing-received=${FILING_RECEIVED_TOPIC:filing-received}
kafka.consumer.topic.filing-processed=${FILING_PROCESSED_TOPIC:filing-processed}

management.endpoints.access.default=none
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.access=read_only
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:https://otel-collector:4318}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:https://otel-collector:4318}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:https://otel-collector:4318}/v1/metrics

api.key.internal=${CHS_INTERNAL_API_KEY:internalApiKey}
api.url.private=${TRANSACTIONS_API_URL:http://localhost:8889}
api.url.kafka=${CHS_KAFKA_API_URL:http://localhost:8889}
api.url.chs=${CHS_URL:http://localhost:8889}
