server.port=${PORT:8081}

kafka.bootstrap-servers=${BOOTSTRAP_SERVER_URL:localhost:9092}

kafka.consumer.retry.max-attempts=${RETRY_MAX_ATTEMPTS:5}
kafka.consumer.retry.backoff-delay=${RETRY_BACKOFF_DELAY:1000}
kafka.consumer.concurrency=${CONSUMER_CONCURRENCY:1}
kafka.consumer.group=${CONSUMER_GROUP:filing-notification-sender}
kafka.consumer.topic.filing-received=${FILING_RECEIVED_TOPIC:filing-received}
kafka.consumer.topic.filing-processed=${FILING_PROCESSED_TOPIC:filing-processed}

management.endpoints.enabled-by-default=false
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true
management.health.mongo.enabled=false
